# Generated by Django 2.2.3 on 2019-07-31 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('off_url', models.TextField()),
                ('category', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mail_address', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=48)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Product')),
                ('image_full_url', models.TextField()),
                ('image_front_url', models.TextField()),
            ],
            options={
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Product')),
                ('nutriscore', models.CharField(max_length=1)),
                ('energy_100g', models.DecimalField(decimal_places=2, max_digits=7)),
                ('energy_unit', models.CharField(max_length=5)),
                ('proteins_100g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fat_100g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('saturated_fat_100g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbohydrates_100g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sugars_100g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fiber_100g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('salt_100g', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'nutrition',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_recorded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recorded_set', to='website.Product')),
                ('product_searched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_searched_set', to='website.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User')),
            ],
            options={
                'db_table': 'record',
            },
        ),
    ]
