# Generated by Django 2.2.4 on 2019-09-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190902_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='product_recorded',
            new_name='substitute',
        ),
    ]
