# Generated by Django 2.2.4 on 2019-09-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190905_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='product_searched',
        ),
    ]
