# Generated by Django 2.2.3 on 2019-07-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NutritionPanel',
            new_name='Nutrition',
        ),
        migrations.AlterModelTable(
            name='nutrition',
            table='nutrition',
        ),
    ]
