# Generated by Django 2.2.3 on 2019-07-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='nutritionpanel',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='user_id',
            new_name='user',
        ),
    ]
